### ISSUE TITLE
Add Clickable Icons in trailingRowOptions

### ISSUE THREAD

**Issue by UmarEhsan** [quicktype/glide-data-grid#654]
I'm a beginner at using canvas. glide-data-grid.

We need to add a clickable icon in the trailingRowOptions like this.
We have a requirement to make an icon that is clickable also.
Is there any way we can achieve this by trailingRowOptions or is there any other workaround?

![image](https://user-images.githubusercontent.com/14802705/221629173-99a9ac90-ee6b-4f0a-bd82-9f6c21eff4ca.png)

we need to add a clickable icon here on the right side.
![image](https://user-images.githubusercontent.com/14802705/221630448-70f18872-887a-4cdf-93b4-727a29cbfef0.png)

**Comment by jassmith** [comment]
Instead of using the built in trailing row, build your own with DOM elements. The default trailing row does not support this.
