### ISSUE TITLE
rightElement breaks the resizing behavior for the last column

### ISSUE THREAD

**Issue by nightire** [quicktype/glide-data-grid#661]
Having the right element breaks the resizing on the last column because when dragging toward the right element, the pointer will hover over the right element instead of the header row.

Adding a little extra overscrollX can be a workaround here, but:

1. user still needs to be careful not to drag the mouse too fast. Once the pointer moves to the right element other than the header row, resizing is broken
2. it isn't pleasant in the manner of UI

1st demo: right element breaks the resizing
https://user-images.githubusercontent.com/1104018/223632768-0632ffa9-4a13-4ea2-ab46-c109bb727113.mp4

2nd demo: extra overscrollX workaround
https://user-images.githubusercontent.com/1104018/223636749-9a4524fb-a775-41e8-9807-dfdb8a88e06a.mp4

**Comment by jassmith** [comment]
This is resolved in 5.3.1 alpha
