### ISSUE TITLE
If a cell is set to readonly, the cell below it cannot be modified by typing

### ISSUE THREAD

**Issue by elloodev** [quicktype/glide-data-grid#679]
I noticed if a cell is set as readonly, the cell below it cannot be modified by typing. If I double click on it, it opens the overlay and I'm able to edit. In the following codesandbox only the "Product 1" cell is set as readonly, but if I try to type directly in the "Product 2" cell, the value doesn't change: [https://codesandbox.io/s/hopeful-heisenberg-fvk92y](https://codesandbox.io/s/hopeful-heisenberg-fvk92y)

**Comment by pzcfg** [comment]
Weirder still, if I change your sandbox example to the second row ("Product 2") I can sometimes get it to edit anyway, although seemingly only to a single character at a time.

https://user-images.githubusercontent.com/94077014/233207650-92be575e-e83c-4df0-aa1b-30d64049c008.mp4

**Comment by jassmith** [comment]
This should be fixed in 5.3.1
