### ISSUE TITLE
DataEditor scrolls when mouse is pressed down on column header

### ISSUE THREAD

**Issue by timobetina** [quicktype/glide-data-grid#681]
When the mouse is pressed down on a column header, the grid scrolls vertically. It is mainly apparent when re-ordering columns.

This issue can be observed in any of the Storybook demos.

Attaching a gif with the issue.:

![scrollOnMouseDown](https://user-images.githubusercontent.com/8442348/228887306-4358b46f-9e00-45b7-ad8b-571cebf4eefa.gif)

**Comment by jassmith** [comment]
This is fixed in 5.2.2 beta
