### ISSUE TITLE
Cannot edit the last column cells within the  v5.2.2-beta4 version

### ISSUE THREAD

**Issue by aramvr** [quicktype/glide-data-grid#682]
[This commit](https://github.com/glideapps/glide-data-grid/commit/caad51c217f79b66777d66a0a14cf984ffba9e46#diff-3e4b00d273a625e520929f36335bd67bab65f8c4c042a4a56b580c1fc706e2e0R3331) introduced an issue that prevents editing the last column cells, which can be reproduced [here in the storybook](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--add-columns).

**Comment by BrianHung** [comment]
Think its a off-by-one error with `rowMarkerOffset`:
```js
    const selectionOutOfBounds =
        gridSelection.current !== undefined &&
        (gridSelection.current.cell[0] >= columnsIn.length + rowMarkerOffset || gridSelection.current.cell[1] >= mangledRows);
```

**Comment by jassmith** [comment]
This is resolved now
