### ISSUE TITLE
Removing extra/empty rows and columns

### ISSUE THREAD

**Issue by highviolet** [quicktype/glide-data-grid#688]
Hi,

I've been looking for a solution for hiding the extra/empty row and column as created by default.

Starting from the example at https://codesandbox.io/s/glide-data-grid-template-ydvnnk, I tried adding `overscrollX={0} overscrollY={0}` but it doesn't alter the table.

I checked #159 and #160 and guessed that setting the overscroll to 0 would remove the empty row/column.

This screenshot shows what is produced by the sandbox example.
![Untitled](https://user-images.githubusercontent.com/45597004/231546447-6569b257-8c44-411f-bdba-2ca2669871a0.png)

**Comment by pzcfg** [comment]
What browser and OS are you using? And have you changed your zoom level?

I tried in the latest Chrome and Safari on macOS 13.3.1 and I don't see these extra rows/columns in the sandbox link above, either with or without `overscrollX/Y={0}` set.

**Comment by highviolet** [comment]
This is on Windows 10, using Microsoft Edge Version 112.0.1722.58

**Comment by hkang1** [comment]
here's another data point for a table that shows all the extra rows
<img width="1266" alt="Screenshot 2023-06-12 at 11 08 38 AM" src="https://github.com/glideapps/glide-data-grid/assets/220971/fb22a152-2714-41a7-a69b-a047262ee110">

**Comment by jassmith** [comment]
On windows what you are seeing is the non-overlay scrollbar trough room being allocated for. As for the extra rows, the best I can offer is simply let the grid expand vertically instead of forcing its sizing.

**Comment by jrweinb** [comment]
Hello - I am experiencing the same issue. When viewing the sandbox ( https://codesandbox.io/s/glide-data-grid-template-ydvnnk )  on Mac, I get no overscroll column, but when viewed on Windows I do get the extra column. If you can point me to the right place in the code, I am happy to try to patch it. Thanks!
