### ISSUE TITLE
onCellClicked checks click originated in cell (lastMouseDown) but not custom renderers

### ISSUE THREAD

**Issue by mapmeld** [quicktype/glide-data-grid#690]
Hey 👋 huge fan of the tables made with this.
We're working on a project with some custom cell renderers, including the links-cell renderer from this repo

Ran into an issue where if someone clicks and drags, `onCellClicked` checks if `lastMouseDown` originated the click in the same cell https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/data-editor.tsx#L2012 , but continues to call the custom cell renderers' `onClick` without additional information.

Would like to see either of these:
- same rule applied to blocking `onClick` as there is for `onCellClicked`
- additional information in the custom renderer `onClick` call / event to make it possible to check if event was triggered by same as the `lastMouseDown`

**Comment by jassmith** [comment]
Fixed in 5.3.1
