### ISSUE TITLE
New Column Button and previous column hover issues

### ISSUE THREAD

**Issue by mdvictor** [quicktype/glide-data-grid#696]
Hello!

I'm having trouble with the last column and the new col button. When hovering from the last column towards the button, both elements remain hovered. Only the button element should be hovered though. E.g from the storybook:

https://user-images.githubusercontent.com/36818606/235897844-76ced9b9-1f0c-4a0d-94e0-112d404e5656.mov

Can you please help me with this?

**Comment by jassmith** [comment]
Fixed in 5.3.1
