### ISSUE TITLE
`measureCell` is not allowing custom cells (`GridCellKind.Custom`) to actually calculate the cell width

### ISSUE THREAD

**Issue by hkang1** [quicktype/glide-data-grid#697]
[Relevant PR](https://github.com/glideapps/glide-data-grid/pull/703)
[Relevant line](https://github.com/glideapps/glide-data-grid/blob/f1d23fe54ea95e92639d4857a51ff57d1555df98/packages/core/src/data-editor/use-column-sizer.ts#L24)

```
function measureCell(
    ctx: CanvasRenderingContext2D,
    cell: GridCell,
    theme: Theme,
    getCellRenderer: GetCellRendererCallback
): number {
    if (cell.kind === GridCellKind.Custom) return defaultSize;

    const r = getCellRenderer(cell);
    return r?.measure?.(ctx, cell, theme) ?? defaultSize;
}
```

The line `if (cell.kind === GridCellKind.Custom) return defaultSize;` here skips any measurement and returns a constant value of `150` when the cell type is of `GridCellKind.Custom`. Shouldn't this line just get removed and allow users to define measuring callbacks?

**Comment by chkn** [comment]
Closing since the fix was merged.
