### ISSUE TITLE
lost focus

### ISSUE THREAD

**Issue by temaivanoff** [quicktype/glide-data-grid#702]
Hi, if you enter numbers one after another `1`, `2` length 1, then the focus is lost and scroll occurs. 

https://github.com/glideapps/glide-data-grid/assets/11176223/383e7329-a3c0-46a8-a891-38fd596e72e4

**Comment by jassmith** [comment]
This does not reproduce in 5.2.2. I can't repro on older versions either... I think there might be an issue with your implementation.
