### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by AndrewSagorski** [quicktype/glide-data-grid#708]
Hi! Firstly wanted to say thanks for this awesome project, been getting a lot of value from it. Have a niche issue that I've run into, was wondering if I could get some eyes on it:

Encountering a ERR_REQUIRE_ESM when importing from commonjs:
`Error [ERR_REQUIRE_ESM]: require() of ES Module C:\...\@glideapps\glide-data-grid\dist\cjs\index.js from C:\reproduce\file.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs"`

Reproduced with tsconfig.json
`{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "sourceMap": true,
    "inlineSources": true,
    "rootDir": ".",
    "baseUrl": ".",
    "target": "es5",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictNullChecks": true,
    "allowJs": true,
    "lib": [
      "esnext",
      "dom"
    ]
  }
}`

and basic ts file 
`import * as g from "@glideapps/glide-data-grid";
console.log(g.GridCellKind.Boolean);`
If I add a package.json file containing  `{ "type": "commonjs" }` in the dist/cjs then the import works.

Cheers, and thanks again for an awesome project.

**Comment by jassmith** [comment]
we will fix this when it feels like all the damn bundlers out there have figured out whatever the hell they want. Until then we are going to let people figure out hwo to configure their bundler to accept this. I have relatively up to date demo projects to ensure things work.
