### ISSUE TITLE
Sorting with glideapps/glide-data-grid-source

### ISSUE THREAD

**Issue by SourceCipher** [quicktype/glide-data-grid#709]
First of all, thanks for this great component you guys built! Examples and all looks great and we are going to run loads of tests on this table to see if its possible to integrate within our platform.

As I read from the docs there is no column filter yet, which I think for the table is one of the core functionalities, so hopefully this will be added very soon. Also I found that its possible to sort the columns but there is no examples or documentation of how to integrate it. I understand that we have to use `glideapps/glide-data-grid-source` package for that, but I cant find what to import from it or how to use this in any way. Any information of how do we implement the column sorting?

**Comment by jassmith** [comment]
You can ask for help over here: https://github.com/quicktype/glide-data-grid/discussions
