### ISSUE TITLE
Project maintenance status

### ISSUE THREAD

**Issue by KyDenZ** [quicktype/glide-data-grid#712]
I'm interested in using the package. However, the project appears not to have been updated for several months and there are several MRs awaiting validation.

I'd like to know if the project is still being actively maintained. If so, I'd be delighted to contribute to the project by helping to resolve pending MRs or by making other improvements. However, it is important for me to make sure that the project is still active and that there is an intention to continue its development.

Thank you very much.

**Comment by tb-viktor** [comment]
It is the same for us. It was a lot of work to migrate our product to this library. It seemed like the best choice for excel-like data tables, but suddenly library development completely stopped. We figured that the focus shifted temporarily, but we are increasingly worried that it will end up abandoned.

**Comment by pzcfg** [comment]
It seems like they've been busy preparing for a big launch https://twitter.com/glideapps/status/1666090273930375170 so I'm hoping they'll be back soon 🙂

**Comment by BrianHung** [comment]
The library seems pretty stable. I’m using patch-package for some custom behavior but beyond that I’ve been pretty happy with it.

**Comment by rfdrake27** [comment]
The storybook is now a 404 page so I am not positive on this library being maintained.

**Comment by KyDenZ** [comment]
The repo owner has changed. Here is the new link:

https://quicktype.github.io/glide-data-grid/

**Comment by rfdrake27** [comment]
Do you know the reason for the change? What is the relationship between Glide and Quicktype?

**Comment by KyDenZ** [comment]
quicktype is made up of two people, including @schani who occupies the role of CTO at Glide.

**Comment by rfdrake27** [comment]
Hm ok. Looking at the quicktype/quicktype repo it looks like they have said it is no longer maintained. I wonder if it has been moved into a collection of unmaintained repos then.

**Comment by AndreRLima** [comment]
Hopefully, they start maintaining it again, it seems to be a quite good library and the default tables are beautiful. Does someone know any other option?

**Comment by pzcfg** [comment]
Hey @dvdsgl just wanted to check if you have plans or a rough timeline for working through the backlog of PRs and issues?

**Comment by dvdsgl** [comment]
Hello!

`quicktype` is the legacy organization we use at Glide, and we're consolidating repos to improve our security.

We have no short term plans to work on `glide-data-grid` OSS project, and we will likely make the repo read-only. We're sad that we don't have time to manage the open-source project–it's pretty popular, and even some Glide competitors use it!

**Comment by LukasMasuch** [comment]
I would also be happy to help with project maintenance

**Comment by dvdsgl** [comment]
We'll consider it! Thank you for the support. We haven't decided what to do yet.
