### ISSUE TITLE
One million rows demo broken

### ISSUE THREAD

**Issue by trevorgithub** [quicktype/glide-data-grid#714]
Steps to reproduce:

1. Navigate to Storybook page: https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--one-million-rows
2. Initially the grid appears populated with many rows
3. After a short delay, the grid is cleared and then partially repopulated with 5 rows.

I'm using MS Edge 114 on Windows 10

**Comment by anshdube10801** [comment]
![glide data grid](https://github.com/glideapps/glide-data-grid/assets/68386918/17ab463a-cdf4-49b6-9353-dc52d8fdda2c)

No, this is because in the code below there is setTimeOut implemented which limits the rows to 5 after 3 second.

**Comment by trevorgithub** [comment]
Ah, I see now that is true.  Why does the demo do that?  There's no reference to that in the description and it's counterintuitive for a demo that says One Million Rows.  My expectation would be that the demo lets the end user play with a grid that has many (1 million+) rows, rather than just 5.

**Comment by pzcfg** [comment]
Looking at the commit that added this https://github.com/glideapps/glide-data-grid/commit/caad51c217f79b66777d66a0a14cf984ffba9e46 I suspect this demo was used in testing the ghost selection clearing and was not meant to be committed. @jassmith can you confirm?

**Comment by pzcfg** [comment]
Created #715 to revert the change
