### ISSUE TITLE
How to Set column width automatically?

### ISSUE THREAD

**Issue by bannarisoftwares** [quicktype/glide-data-grid#718]
How to make column width automatically based on content in glide-data-grid in react js?
```[tasklist]
### Tasks
```

**Comment by BrianHung** [comment]
There’s logic in the codebase to double click to automatically resize. Try that to compute col widths before passing it into glide.

**Comment by pzcfg** [comment]
Version 4.0.0 introduced a [useColumnSizer](https://grid.glideapps.com/docs/functions/useColumnSizer.html) that lets you auto-size [AutoGridColumn](https://grid.glideapps.com/docs/interfaces/AutoGridColumn.html)s. One little tricky detail that I missed when I was trying to test #717 is that the auto sizing requires `getCellsForSelection` to be defined. Ideally you should build your own proper cached version of this function, but you can also use `getCellsForSelection={true}` which uses an internal version that queries `getCellContent`.

Here's a modified version of the codesandbox example that uses the autosizing:

https://codesandbox.io/s/glide-data-grid-autosized-columns-fc6xk2?file=/src/App.tsx:1324-1338
