### ISSUE TITLE
onItemHovered doesn't respect whether the grid is obscured by other elements

### ISSUE THREAD

**Issue by holloway** [quicktype/glide-data-grid#731]
When an element obscures the grid  the `onItemHovered` callback is still called. Ie a modal with a transparent overlay covering the whole grid will still trigger the "hover" event callback.

I think this is because [the `mousemove` event is registered on `window`](https://github.com/glideapps/glide-data-grid/blob/c9e1f3df5d545171ccca2226c0c55e253fb6cc83/packages/core/src/data-grid/data-grid.tsx#LL1124C3-L1124C3) not the  `<canvas>` element, and so there's no knowledge of whether other elements obscure the grid.

So this GitHub issue is requesting a change to ensure `onItemHovered` only fires when the mouse is over the grid and not obscured by other elements, or that the callback is given an additional arg to indicate whether the`<canvas>` is obscured.

Some possible ways of addressing this are:
1. Inside the mousemove callback use [`document.elementFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint) (ie `window.elementFromPoint(event.clientX, event.clientY)` to check whether the returned element is the `<canvas>`; or
2. Register `mousemove` on the `<canvas>` instead so that the browser handles`<canvas>` obscuring and doesn't trigger events; or
3. Use `mouseenter/leave` (not `mouseover/out` as that misses events) on the canvas to set some boolean of whether the mouse is over the `<canvas>`.

A coworker says that the header cells have the same issue, so that might need to be solved too. Would you like another issue raised for that?

**Comment by jassmith** [comment]
There was a reason why the handlers are not on the canvas. Younger version of me remember why. Smarter versions of me wish I had documented that reason. Current me just spites past me for not writing it down.

**Comment by jassmith** [comment]
This was fixed by another community PR.

**Comment by jassmith** [comment]
I have put in some changes to how this works. We do need these events in some cases to prevent issues with click off/selection. I think we've found a happy medium.

**Comment by holloway** [comment]
Thanks @jassmith which PR was it that addressed this?
