### ISSUE TITLE
Feature request: cut selected cells using `Ctrl+X` / `Command+X`

### ISSUE THREAD

**Issue by romanstetsyk** [quicktype/glide-data-grid#733]
`glide-data-grid` currently provides an excellent copy/paste feature allowing users to duplicate cells' content easily. However, no cut functionality is available to remove selected cells' content in one step using the `Ctrl+X` or `Command+X` keyboard shortcuts.
Benefits: It will improve the usability of apps that use `glide-data-grid` and make the interface more familiar. Given that there are shortcuts `Ctrl+C` and `Ctrl+V`, users might also expect `Ctrl+X` to work.
Thanks for your hard work!

**Comment by jassmith** [comment]
Added in 5.3.1
