### ISSUE TITLE
blur text when dragging

### ISSUE THREAD

**Issue by sunnipaul** [quicktype/glide-data-grid#741]
When dragging on Retina display,  the dragged text becomes blur. 
Is there any way to make it clear ?  
Can I customize the text or image being dragged?

BTW: Great  data grid I ever seen.  
![drag-blur-2](https://github.com/glideapps/glide-data-grid/assets/5299443/c0be0e1d-9a2e-4f1c-84d9-19873946a65a)

**Comment by jassmith** [comment]
Probably wont fix for quite some time. I think this requires we ensure to render a hi-dpi image and ensure the browser knows it is hidpi which I didn't want to figure out how to do.

**Comment by jassmith** [comment]
Fixed in 5.3.1
