### ISSUE TITLE
Storybook is no longer accessible online

### ISSUE THREAD

**Issue by lloan** [quicktype/glide-data-grid#745]
I can't seem to access the storybook for this project online. Is there an alternative link or access point?

**Comment by rfdrake27** [comment]
Yea it's a significant problem when the repo constantly mentions to check out the example in storybook...

**Comment by lloan** [comment]
> The repo owner has changed. Here is the new link:
> 
> https://quicktype.github.io/glide-data-grid/

Oh man, you would have saved me so much time this weekend. Thanks a ton!
