### ISSUE TITLE
Error-prone escape() change

### ISSUE THREAD

**Issue by pzcfg** [quicktype/glide-data-grid#761]
Looking at https://github.com/quicktype/glide-data-grid/commit/e499181c4c23cb981b3fd72f506f3e89a0701786 this change to `escape()` feels exceedingly error-prone, especially since the default `escape(string)` does not escape at all.

https://github.com/quicktype/glide-data-grid/blob/e499181c4c23cb981b3fd72f506f3e89a0701786/packages/core/src/data-editor/data-editor-fns.ts#L206-L212

It seems like it would be better to explicitly escape/not escape in the function below, e.g.
```patch
         case GridCellKind.Custom:
-            return escape(cell.copyData, escapeValues);
+            return escapeValues ? escape(cell.copyData) : cell.copyData;
```
Or to make some sort of separate `conditionallyEscape(string, shouldEscape)`
Or at the very least have `escape(string)` default to escaping (i.e. `function escape(str: string, actuallyEscape: boolean = true): string {`)

**Comment by jassmith** [comment]
the default? the actuallyEscape parameter is required. Still, happy to rework this for clarity.

**Comment by jassmith** [comment]
Resolved
