### ISSUE TITLE
Click on a scrollbar unselects selected rows

### ISSUE THREAD

**Issue by Higgy831** [quicktype/glide-data-grid#762]
If you click on a scrollbar (Or if you click inside the canvas but not actually on a cell/header/row) the selected rows getting unselected.
This was no issue in 5.2.1.

You can reproduce this behavior it the storybook:
https://quicktype.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--multi-select-columns
I would say it should only be possible to unselect a row via the rowMarkers!?

Would be great if this can be fixed. ;)

Thank you, for the awesome GlideTables!

**Comment by jassmith** [comment]
Yes will fix

**Comment by jassmith** [comment]
Fixed in 5.3.1
